{{- if .Values.PodDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}
  namespace: {{.Release.Namespace}}
spec:
  minAvailable: {{ .Values.PodDisruptionBudget.minimumCount }}
  selector:
    matchLabels:
{{ include "ms-auto-release.labels" . | indent 6 }}
{{- end }}