apiVersion: v1
kind: Service
metadata:
  name: {{ include "ms-auto-release.fullname" . }}
  labels:
{{ include "ms-auto-release.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
{{ include "ms-auto-release.labels" . | indent 4 }}

